// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gzapjsbpymfmliurdqen.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd6YXBqc2JweW1mbWxpdXJkcWVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1NDk3NzIsImV4cCI6MjA3NDEyNTc3Mn0.Fbp2rqbY8IYBDOcuq1I997aTGxN2m234SUToRU92sk4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});